### ISSUE TITLE
Sugestão para o ReadMe =)

### ISSUE THREAD

**Issue by DrikaDev** [gabrielfroes/byebg#1]
Oi Gabriel, tudo bom?
Primeiramente parabéns pelo projeto!
Segundo, gostaria de deixar uma sugestão pro seu ReadMe:

1) diminuir uns 20% / 30% o tamanho da sua img desse logo, achei ele bem grande, meu ponto de vista ta bom?
<img width="218" alt="image" src="https://github.com/gabrielfroes/byebg/assets/102387476/f402a9d5-cad5-4376-a54b-f28e359648a2">

2) seria legal, visualmente falando, por uma setinha apontando ali pro Remover Fundo:
<img width="291" alt="image" src="https://github.com/gabrielfroes/byebg/assets/102387476/2c89d549-feb8-4c21-9a29-834fca8fa915">
(Confesso que qd bati o olho ali eu não entendi o Menu de Contexto rs)

Bom, era só isso mesmo.
Peço perdão se a sugestão é sem noção rs, é que eu sou bem jr ainda.
Um grande abraço da sua nova fã!
DrikaDev =)

**Comment by gabrielfroes** [comment]
Tem razão, fiz as alterações e realmente ficou melhor.
